export interface SearchIndexItem {
  id: string;
  title: string;          // 타이틀 (한글/영문 컴포넌트 및 서식 제목)
  subTitle?: string;       // 세부 타이틀 / 설명
  path: string;            // 이동할 URL 라우트
  categoryKey: string;     // 카테고리 식별자
  categoryName: string;    // 카테고리 표시 이름
  parentMenuName?: string; // 상위 메뉴 이름
  iconName: string;        // Lucide 아이콘 이름
  keywords: string[];      // 검색 키워드/태그 리스트
  badge?: string;          // 배지
}

export const searchableIndex: SearchIndexItem[] = [
  // ----------------------------------------------------
  // 1. 대시보드 (Dashboard)
  // ----------------------------------------------------
  {
    id: 'dashboard_main',
    title: '대시보드 메인',
    subTitle: '월별 컴포넌트 추이 / 고객 인구 통계 / 최근 주문 현황',
    path: '/',
    categoryKey: 'dashboard',
    categoryName: '대시보드',
    iconName: 'LayoutDashboard',
    keywords: ['대시보드', '메인', '월별', '추이', '인구통계', '최근주문', '통계', '차트', 'dashboard'],
  },
  {
    id: 'dashboard_recent_orders',
    title: '최근 주문 및 개발 활동 로그',
    subTitle: '대시보드 내 최근 컴포넌트 업데이트 및 커밋 히스토리',
    path: '/',
    categoryKey: 'dashboard',
    categoryName: '대시보드',
    iconName: 'LayoutDashboard',
    keywords: ['주문', '활동', '로그', '커밋', '히스토리', '업데이트', '개발'],
  },

  // ----------------------------------------------------
  // 2. 히어로 섹션 세부 컴포넌트 (Hero Sections)
  // ----------------------------------------------------
  {
    id: 'hero_yongin',
    title: '용인디지털기록관 히어로 (바닐라 JS & Tailwind)',
    subTitle: '용인디지털기록관 메인 페이드 슬라이더 및 타이틀 비주얼 히어로 컴포넌트',
    path: '/pages/hero-sections',
    categoryKey: 'pages',
    categoryName: '페이지 컴포넌트',
    parentMenuName: '페이지 > 히어로 섹션',
    iconName: 'Layers',
    keywords: ['용인디지털기록관', '용인디지털기록관 히어로', '용인', '기록관', '임진산성', '처인성', '슬라이더', '페이드', 'hero', '디지털기록관'],
    badge: 'NEW',
  },
  {
    id: 'hero_centered',
    title: '간단한 중앙 정렬 히어로',
    subTitle: '모던 텍스트 배치 및 행동 유도(CTA) 버튼 중앙 히어로 컴포넌트',
    path: '/pages/hero-sections',
    categoryKey: 'pages',
    categoryName: '페이지 컴포넌트',
    parentMenuName: '페이지 > 히어로 섹션',
    iconName: 'Layers',
    keywords: ['중앙정렬', '히어로', 'cta', '텍스트히어로', '중앙', 'simple hero'],
  },
  {
    id: 'hero_split',
    title: '클래식 분할 배치 히어로',
    subTitle: '좌측 타이틀 설명 텍스트, 우측 이미지 그래픽 분할 히어로',
    path: '/pages/hero-sections',
    categoryKey: 'pages',
    categoryName: '페이지 컴포넌트',
    parentMenuName: '페이지 > 히어로 섹션',
    iconName: 'Layers',
    keywords: ['분할', '클래식', '이미지히어로', '좌우분할', 'split hero'],
  },
  {
    id: 'hero_elegant',
    title: '우아한 분위기의 중앙 정렬 히어로',
    subTitle: '글래스모피즘 및 다크 모드 스타일이 적용된 프리미엄 비주얼 히어로',
    path: '/pages/hero-sections',
    categoryKey: 'pages',
    categoryName: '페이지 컴포넌트',
    parentMenuName: '페이지 > 히어로 섹션',
    iconName: 'Layers',
    keywords: ['우아한', '프리미엄', '글래스모피즘', 'dark hero', 'elegant hero'],
  },
  {
    id: 'hero_search',
    title: '검색 포커스형 가이드 히어로 (Search Oriented Hero)',
    subTitle: '중앙 대형 검색창 및 인기 키워드 태그가 포함된 검색 가이드 히어로',
    path: '/pages/hero-sections',
    categoryKey: 'pages',
    categoryName: '페이지 컴포넌트',
    parentMenuName: '페이지 > 히어로 섹션',
    iconName: 'Layers',
    keywords: ['검색', '검색포커스', '검색형히어로', 'search hero', '인기검색어', '가이드'],
  },
  {
    id: 'hero_minimal',
    title: '미니멀 이미지 배경 히어로',
    subTitle: '깔끔하고 정돈된 비주얼 배경 히어로 섹션',
    path: '/pages/hero-sections',
    categoryKey: 'pages',
    categoryName: '페이지 컴포넌트',
    parentMenuName: '페이지 > 히어로 섹션',
    iconName: 'Layers',
    keywords: ['미니멀', '배경이미지', 'minimal hero', '깔끔한'],
  },

  // ----------------------------------------------------
  // 3. 테이블 세부 컴포넌트 (Tables)
  // ----------------------------------------------------
  {
    id: 'table_recent_orders',
    title: '최근 주문 테이블 (Recent Orders Table)',
    subTitle: '체크박스, 거래 ID, 고객 정보, 마감일, 상태 배지가 포함된 테이블',
    path: '/tables/basic',
    categoryKey: 'tables',
    categoryName: '테이블 컴포넌트',
    parentMenuName: '테이블 > 기본 테이블',
    iconName: 'Table',
    keywords: ['최근주문', '주문테이블', '고객목록', 'orders table', '거래ID', '체크박스'],
    badge: '5',
  },
  {
    id: 'table_recent_transactions',
    title: '최근 거래 내역 테이블 (Recent Transactions Table)',
    subTitle: '아이콘, 카테고리, 거래 금액, 처리 상태 표기 테이블',
    path: '/tables/basic',
    categoryKey: 'tables',
    categoryName: '테이블 컴포넌트',
    parentMenuName: '테이블 > 기본 테이블',
    iconName: 'Table',
    keywords: ['최근거래', '거래내역', '입출금', 'transactions table', '금융테이블'],
  },

  // ----------------------------------------------------
  // 4. 폼 세부 컴포넌트 (Forms)
  // ----------------------------------------------------
  {
    id: 'form_basic_inputs',
    title: '기본 입력란 (Basic Inputs)',
    subTitle: '텍스트, 이메일, 비밀번호, 플레이스홀더 기본 입력 인풋 컴포넌트',
    path: '/forms/elements',
    categoryKey: 'forms',
    categoryName: '폼 컴포넌트',
    parentMenuName: '폼 > 폼 요소',
    iconName: 'SquarePen',
    keywords: ['기본입력란', '인풋', 'input', 'text input', '비밀번호', '이메일'],
    badge: '9',
  },
  {
    id: 'form_select_options',
    title: '선택 입력란 (Select Options)',
    subTitle: '드롭다운 단일/다중 선택 옵션 컴포넌트',
    path: '/forms/elements',
    categoryKey: 'forms',
    categoryName: '폼 컴포넌트',
    parentMenuName: '폼 > 폼 요소',
    iconName: 'SquarePen',
    keywords: ['선택입력란', '셀렉트', 'select', '드롭다운', 'option'],
  },
  {
    id: 'form_textarea',
    title: '텍스트 영역 (Textarea)',
    subTitle: '장문의 글 작성용 텍스트에리어 입력 필드',
    path: '/forms/elements',
    categoryKey: 'forms',
    categoryName: '폼 컴포넌트',
    parentMenuName: '폼 > 폼 요소',
    iconName: 'SquarePen',
    keywords: ['텍스트영역', 'textarea', '장문입력', '본문작성'],
  },
  {
    id: 'form_input_groups',
    title: '입력 그룹 (Input Groups)',
    subTitle: '접두사/접미사 아이콘, 버튼 결합형 인풋 그룹',
    path: '/forms/elements',
    categoryKey: 'forms',
    categoryName: '폼 컴포넌트',
    parentMenuName: '폼 > 폼 요소',
    iconName: 'SquarePen',
    keywords: ['입력그룹', 'input group', '아이콘인풋', '검색인풋'],
  },
  {
    id: 'form_file_upload',
    title: '파일 업로드 & 드롭존 (File Upload & Dropzone)',
    subTitle: '파일 선택 및 인라인 드래그 앤 드롭 파일 첨부 컴포넌트',
    path: '/forms/elements',
    categoryKey: 'forms',
    categoryName: '폼 컴포넌트',
    parentMenuName: '폼 > 폼 요소',
    iconName: 'SquarePen',
    keywords: ['파일업로드', '드롭존', 'file upload', 'dropzone', '첨부파일'],
  },
  {
    id: 'form_checkbox_radio',
    title: '체크박스 & 라디오 버튼 & 토글 스위치',
    subTitle: '다중 선택 체크박스, 단일 선택 라디오, ON/OFF 스위치 컨트롤',
    path: '/forms/elements',
    categoryKey: 'forms',
    categoryName: '폼 컴포넌트',
    parentMenuName: '폼 > 폼 요소',
    iconName: 'SquarePen',
    keywords: ['체크박스', '라디오', '스위치', 'checkbox', 'radio', 'switch', 'toggle'],
  },
  {
    id: 'form_signup_layout',
    title: '회원가입 & 상세 개인정보 입력 폼 레이아웃',
    subTitle: '이름, 주소, 연락처, 카드 결제 입력 종합 폼 서식',
    path: '/forms/layout',
    categoryKey: 'forms',
    categoryName: '폼 컴포넌트',
    parentMenuName: '폼 > 폼 레이아웃',
    iconName: 'SquarePen',
    keywords: ['회원가입폼', '개인정보폼', '주소폼', 'signup form', 'layout form'],
    badge: '4',
  },

  // ----------------------------------------------------
  // 5. 웹진 - 이음 세부 컴포넌트 (Eeum Webzine Sub-Components)
  // ----------------------------------------------------
  {
    id: 'ieum-text-temp-12',
    title: '이음 - 번호 태그형 밑줄 제목 (#1. 장애인·비장애인 협업)',
    subTitle: '일련번호와 두 줄 제목이 들어간 밑줄형 타이틀 영역',
    path: '/webzine/eeum/text',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 이음 > 텍스트',
    iconName: 'BookOpen',
    keywords: ['이음', '번호태그형', '밑줄제목', '장애인', '비장애인', '협업', 'eeum'],
    badge: '18',
  },
  {
    id: 'ieum-text-temp-13',
    title: '이음 - 중앙 정렬 밑줄 제목 (정책과 제도, 접근성의 시대)',
    subTitle: '가운데 정렬된 굵은 밑줄 제목 타이틀 서식',
    path: '/webzine/eeum/text',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 이음 > 텍스트',
    iconName: 'BookOpen',
    keywords: ['이음', '중앙정렬', '접근성', '정책과제도', '밑줄제목'],
  },
  {
    id: 'ieum-text-temp-14',
    title: '이음 - 화자 표시 대화 본문 단락',
    subTitle: '앞단에 화자 이름이 굵게 강조되는 대화 또는 인터뷰 본문 단락',
    path: '/webzine/eeum/text',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 이음 > 텍스트',
    iconName: 'BookOpen',
    keywords: ['화자표시', '인터뷰', '대화단락', '김상미', '조화영'],
  },
  {
    id: 'ieum-text-temp-52',
    title: '이음 - 중앙 정렬 감상 수필 텍스트 단락',
    subTitle: '가운데 정렬 속성이 적용된 여러 행의 수필 또는 시 감상 본문 단락',
    path: '/webzine/eeum/text',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 이음 > 텍스트',
    iconName: 'BookOpen',
    keywords: ['수필', '감상텍스트', '시감상', '몸', '중앙정렬본문'],
  },
  {
    id: 'ieum-box-temp-01',
    title: '이음 - 강조 라인 테두리 박스 양식',
    subTitle: '웹진 이음 주요 강조 내용 테두리 박스 서식',
    path: '/webzine/eeum/box',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 이음 > 박스 양식',
    iconName: 'BookOpen',
    keywords: ['이음박스', '테두리박스', '강조박스', 'box'],
    badge: '17',
  },
  {
    id: 'ieum-box-temp-02',
    title: '이음 - 인용구 박스 서식',
    subTitle: '인터뷰 및 저자 발언 강조용 인용문 텍스트 박스',
    path: '/webzine/eeum/box',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 이음 > 박스 양식',
    iconName: 'BookOpen',
    keywords: ['인용구', '인용문', 'quote box', '이음인용구'],
  },
  {
    id: 'ieum-link-temp-01',
    title: '이음 - 오디오 팟캐스트 A의 모든 것 링크 카드',
    subTitle: '비장애인의 장애 감수성을 기르는 본격 문학방송 팟캐스트 페이지 링크',
    path: '/webzine/eeum/link',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 이음 > 링크',
    iconName: 'BookOpen',
    keywords: ['팟캐스트', 'a의모든것', '미디어오디오', '오디오', '이음링크'],
    badge: '3',
  },
  {
    id: 'ieum-video-temp-01',
    title: '이음 - National accessArts Centre 비디오 플레이어',
    subTitle: '유튜브 임베드 비디오 영상 플레이어 및 영상 출처 링크 서식',
    path: '/webzine/eeum/video',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 이음 > 영상',
    iconName: 'BookOpen',
    keywords: ['이음영상', 'accessarts', '유튜브비디오', 'video player'],
    badge: '3',
  },
  {
    id: 'ieum-profile-temp-01',
    title: '이음 - 필진 저자 프로필 카드',
    subTitle: '필진 아바타 이미지, 성함, 소속 및 주요 집필 이력 카드 서식',
    path: '/webzine/eeum/profile',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 이음 > 프로필',
    iconName: 'BookOpen',
    keywords: ['필진소개', '저자프로필', '이음프로필', 'profile card'],
    badge: '14',
  },

  // ----------------------------------------------------
  // 6. 웹진 - 아르떼 세부 컴포넌트 (Arte Webzine Sub-Components)
  // ----------------------------------------------------
  {
    id: 'discussion-tab-2',
    title: '좌담 탭 2개 (아르떼 탭 레이아웃)',
    subTitle: '2개 버튼으로 구성된 아르떼 웹진 좌담 탭 레이아웃 템플릿',
    path: '/webzine/arte/link',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 링크',
    iconName: 'BookOpen',
    keywords: ['좌담 탭 2개', '좌담탭2개', '좌담', '좌담 탭', '탭', '아르떼 탭', 'arte link'],
    badge: '10',
  },
  {
    id: 'discussion-tab-4',
    title: '좌담 탭 4개 (아르떼 탭 레이아웃)',
    subTitle: '4개 버튼으로 구성된 아르떼 웹진 좌담 탭 레이아웃 템플릿',
    path: '/webzine/arte/link',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 링크',
    iconName: 'BookOpen',
    keywords: ['좌담 탭 4개', '좌담탭4개', '좌담', '좌담 탭', '탭', 'arte link'],
  },
  {
    id: 'discussion-tab-5',
    title: '좌담 탭 5개 (아르떼 탭 레이아웃)',
    subTitle: '5개 버튼으로 구성된 아르떼 웹진 좌담 탭 레이아웃 템플릿',
    path: '/webzine/arte/link',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 링크',
    iconName: 'BookOpen',
    keywords: ['좌담 탭 5개', '좌담탭5개', '좌담', '좌담 탭', '탭', 'arte link'],
  },
  {
    id: 'discussion-image-profile',
    title: '좌담 - 이미지 프로필 (이름 아래 이미지)',
    subTitle: '좌담/토론 참석자 이름과 직함 아래에 프로필 사진이 상하 배치된 템플릿',
    path: '/webzine/arte/new',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > New',
    iconName: 'BookOpen',
    keywords: ['좌담', '좌담 이미지 프로필', '좌담프로필', '이미지프로필', '토론참석자', 'arte new'],
    badge: '12',
  },
  {
    id: 'discussion-overview-lines',
    title: '좌담 개요 (위, 아래 선)',
    subTitle: '위아래 선으로 구분된 깔끔한 좌담 개요 레이아웃 템플릿',
    path: '/webzine/arte/box',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 박스 양식',
    iconName: 'BookOpen',
    keywords: ['좌담 개요', '좌담개요', '좌담', '위아래선', '개요박스', 'arte box'],
    badge: '14',
  },
  {
    id: 'discussion-3-caption',
    title: '3개 (좌담 3명 전체 캡션)',
    subTitle: '좌담 3인 참석자 이미지 및 전체 캡션 레이아웃 템플릿',
    path: '/webzine/arte/image',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 이미지',
    iconName: 'BookOpen',
    keywords: ['좌담 3명', '좌담 3인', '좌담캡션', 'arte image'],
    badge: '16',
  },
  {
    id: 'discussion-4-caption',
    title: '4개 (좌담 전체 캡션)',
    subTitle: '좌담 4인 참석자 이미지 및 전체 캡션 레이아웃 템플릿',
    path: '/webzine/arte/image',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 이미지',
    iconName: 'BookOpen',
    keywords: ['좌담 4명', '좌담 4인', '좌담캡션', 'arte image'],
  },
  {
    id: 'arte-text-temp-01',
    title: '아르떼 - 타이포그래피 예술 칼럼 본문 서식',
    subTitle: '아르떼365 예술 기획 칼럼 및 가독성 높은 기사 본문 텍스트 서식',
    path: '/webzine/arte/text',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 글씨',
    iconName: 'BookOpen',
    keywords: ['아르떼글씨', '예술컬럼', 'arte text', '타이포그래피'],
  },
  {
    id: 'arte-box-temp-01',
    title: '아르떼 - 비욘 나티코 린데블라드 책 소개 박스 (내가 틀릴 수도 있습니다)',
    subTitle: '책 이미지 및 도서 인용구가 들어간 아르떼 프로필형 책 소개 박스 서식',
    path: '/webzine/arte/box',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 박스 양식',
    iconName: 'BookOpen',
    keywords: ['비욘나티코린데블라드', '내가틀릴수도있습니다', '아르떼박스', '책소개박스', 'arte box'],
  },
  {
    id: 'arte-link-temp-01',
    title: '아르떼 - 공유마당 & 아르코 입장문 하이퍼링크 (a 태그 서식)',
    subTitle: '새창 열기 및 언더라인 이펙트가 포함된 커스텀 a 태그 하이퍼링크 서식',
    path: '/webzine/arte/link',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 링크',
    iconName: 'BookOpen',
    keywords: ['공유마당', '아르코', '입장문', 'a태그', '아르떼링크', 'arte link'],
  },
  {
    id: 'arte-notice-temp-01',
    title: '아르떼 - 공지사항 & 이벤트 배너 양식 (Notice & Events)',
    subTitle: '아르떼 365 이벤트 공모전 및 문화예술 교육 공지 배너 양식',
    path: '/webzine/arte/notice',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 공지사항 이벤트',
    iconName: 'BookOpen',
    keywords: ['공지사항', '이벤트', '공모전', 'notice', 'event', 'arte notice'],
    badge: '6',
  },
  {
    id: 'arte-video-temp-01',
    title: '아르떼 - 씨앗의 희망 & 피스오브피스 비디오 플레이어',
    subTitle: '전시 공연 미디어 유튜브 플레이어 및 출처 표기 서식',
    path: '/webzine/arte/video',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 영상',
    iconName: 'BookOpen',
    keywords: ['씨앗의희망', '피스오브피스', '아르떼영상', 'arte video'],
    badge: '4',
  },

  // ----------------------------------------------------
  // 7. 기타 UI 쇼케이스 (UI Showcase Sub-Components)
  // ----------------------------------------------------
  {
    id: 'ui_modals_popups',
    title: '알림창 & 모달 팝업 & 토스트 (Alerts, Modals, Toasts)',
    subTitle: '경고, 성공, 확인 모달 팝업 및 토스트 알림 메시지',
    path: '/ui/alerts-modals',
    categoryKey: 'ui',
    categoryName: 'UI 컴포넌트',
    parentMenuName: 'UI 요소 > 알림 & 모달',
    iconName: 'Component',
    keywords: ['알림', '모달', '팝업', 'modal', 'alert', 'toast', 'dialog'],
    badge: '3',
  },
  {
    id: 'ui_buttons_chips',
    title: '버튼 스타일 & 배지 칩 (Buttons & Badges)',
    subTitle: '프리미엄 컬러 버튼, 로딩 버튼, 상태 배지 태그 모음',
    path: '/ui/buttons-badges',
    categoryKey: 'ui',
    categoryName: 'UI 컴포넌트',
    parentMenuName: 'UI 요소 > 버튼 & 배지',
    iconName: 'Component',
    keywords: ['버튼', '배지', 'button', 'badge', 'chip', '태그'],
    badge: '4',
  },
  {
    id: 'ui_progress_tabs',
    title: '프로그레스바, 탭, 브레드크럼 (Progress & Navigation)',
    subTitle: '진행률 바, 서브 탭 바, 경로 브레드크럼, 단계별 스텝 바',
    path: '/ui/progress-nav',
    categoryKey: 'ui',
    categoryName: 'UI 컴포넌트',
    parentMenuName: 'UI 요소 > 진행률 & 네비게이션',
    iconName: 'Component',
    keywords: ['진행률', '탭', '브레드크럼', 'progress', 'tabs', 'breadcrumb', 'step'],
    badge: '4',
  },
  {
    id: 'ui_skeleton_empty',
    title: '스켈레톤 로더 & 빈 상태 안내 (Skeleton & Empty State)',
    subTitle: '데이터 로딩 시 스켈레톤 애니메이션 및 검색 결과 없음 안내 뷰',
    path: '/ui/states-loaders',
    categoryKey: 'ui',
    categoryName: 'UI 컴포넌트',
    parentMenuName: 'UI 요소 > 상태 & 로더',
    iconName: 'Component',
    keywords: ['스켈레톤', '로더', 'skeleton', 'empty state', '로딩', '빈상태'],
    badge: '2',
  },
];
