export interface SearchIndexItem {
  id: string;
  title: string;          // 타이틀 (한글/영문 컴포넌트 및 서식 제목)
  subTitle?: string;       // 세부 타이틀 / 설명
  path: string;            // 이동할 URL 라우트
  categoryKey: string;     // 카테고리 식별자
  categoryName: string;    // 카테고리 표시 이름
  parentMenuName?: string; // 상위 메뉴 이름
  iconName: string;        // Lucide 아이콘 이름
  keywords: string[];      // 검색 키워드/태그 리스트
  badge?: string;          // 배지
}

export const searchableIndex: SearchIndexItem[] = [
  // ----------------------------------------------------
  // 1. 대시보드 (Dashboard)
  // ----------------------------------------------------
  {
    id: 'dashboard_main',
    title: '대시보드 메인',
    subTitle: '월별 컴포넌트 추이 / 고객 인구 통계 / 최근 주문 현황',
    path: '/',
    categoryKey: 'dashboard',
    categoryName: '대시보드',
    iconName: 'LayoutDashboard',
    keywords: ['대시보드', '메인', '월별', '추이', '인구통계', '최근주문', '통계', '차트', 'dashboard'],
  },
  {
    id: 'dashboard_recent_orders',
    title: '최근 주문 및 개발 활동 로그',
    subTitle: '대시보드 내 최근 컴포넌트 업데이트 및 커밋 히스토리',
    path: '/',
    categoryKey: 'dashboard',
    categoryName: '대시보드',
    iconName: 'LayoutDashboard',
    keywords: ['주문', '활동', '로그', '커밋', '히스토리', '업데이트', '개발'],
  },

  // ----------------------------------------------------
  // 2. 히어로 섹션 세부 컴포넌트 (Hero Sections)
  // ----------------------------------------------------
  {
    id: 'hero_yongin',
    title: '용인디지털기록관 히어로 (바닐라 JS & Tailwind)',
    subTitle: '용인디지털기록관 메인 페이드 슬라이더 및 타이틀 비주얼 히어로 컴포넌트',
    path: '/pages/hero-sections',
    categoryKey: 'pages',
    categoryName: '페이지 컴포넌트',
    parentMenuName: '페이지 > 히어로 섹션',
    iconName: 'Layers',
    keywords: ['용인디지털기록관', '용인디지털기록관 히어로', '용인', '기록관', '임진산성', '처인성', '슬라이더', '페이드', 'hero', '디지털기록관'],
    badge: 'NEW',
  },
  {
    id: 'hero_centered',
    title: '간단한 중앙 정렬 히어로',
    subTitle: '모던 텍스트 배치 및 행동 유도(CTA) 버튼 중앙 히어로 컴포넌트',
    path: '/pages/hero-sections',
    categoryKey: 'pages',
    categoryName: '페이지 컴포넌트',
    parentMenuName: '페이지 > 히어로 섹션',
    iconName: 'Layers',
    keywords: ['중앙정렬', '히어로', 'cta', '텍스트히어로', '중앙', 'simple hero'],
  },
  {
    id: 'hero_split',
    title: '클래식 분할 배치 히어로',
    subTitle: '좌측 타이틀 설명 텍스트, 우측 이미지 그래픽 분할 히어로',
    path: '/pages/hero-sections',
    categoryKey: 'pages',
    categoryName: '페이지 컴포넌트',
    parentMenuName: '페이지 > 히어로 섹션',
    iconName: 'Layers',
    keywords: ['분할', '클래식', '이미지히어로', '좌우분할', 'split hero'],
  },
  {
    id: 'hero_elegant',
    title: '우아한 분위기의 중앙 정렬 히어로',
    subTitle: '글래스모피즘 및 다크 모드 스타일이 적용된 프리미엄 비주얼 히어로',
    path: '/pages/hero-sections',
    categoryKey: 'pages',
    categoryName: '페이지 컴포넌트',
    parentMenuName: '페이지 > 히어로 섹션',
    iconName: 'Layers',
    keywords: ['우아한', '프리미엄', '글래스모피즘', 'dark hero', 'elegant hero'],
  },
  {
    id: 'hero_search',
    title: '검색 포커스형 가이드 히어로 (Search Oriented Hero)',
    subTitle: '중앙 대형 검색창 및 인기 키워드 태그가 포함된 검색 가이드 히어로',
    path: '/pages/hero-sections',
    categoryKey: 'pages',
    categoryName: '페이지 컴포넌트',
    parentMenuName: '페이지 > 히어로 섹션',
    iconName: 'Layers',
    keywords: ['검색', '검색포커스', '검색형히어로', 'search hero', '인기검색어', '가이드'],
  },
  {
    id: 'hero_minimal',
    title: '미니멀 이미지 배경 히어로',
    subTitle: '깔끔하고 정돈된 비주얼 배경 히어로 섹션',
    path: '/pages/hero-sections',
    categoryKey: 'pages',
    categoryName: '페이지 컴포넌트',
    parentMenuName: '페이지 > 히어로 섹션',
    iconName: 'Layers',
    keywords: ['미니멀', '배경이미지', 'minimal hero', '깔끔한'],
  },

  // ----------------------------------------------------
  // 3. 테이블 세부 컴포넌트 (Tables)
  // ----------------------------------------------------
  {
    id: 'table_recent_orders',
    title: '최근 주문 테이블 (Recent Orders Table)',
    subTitle: '체크박스, 거래 ID, 고객 정보, 마감일, 상태 배지가 포함된 테이블',
    path: '/tables/basic',
    categoryKey: 'tables',
    categoryName: '테이블 컴포넌트',
    parentMenuName: '테이블 > 기본 테이블',
    iconName: 'Table',
    keywords: ['최근주문', '주문테이블', '고객목록', 'orders table', '거래ID', '체크박스'],
    badge: '5',
  },
  {
    id: 'table_recent_transactions',
    title: '최근 거래 내역 테이블 (Recent Transactions Table)',
    subTitle: '아이콘, 카테고리, 거래 금액, 처리 상태 표기 테이블',
    path: '/tables/basic',
    categoryKey: 'tables',
    categoryName: '테이블 컴포넌트',
    parentMenuName: '테이블 > 기본 테이블',
    iconName: 'Table',
    keywords: ['최근거래', '거래내역', '입출금', 'transactions table', '금융테이블'],
  },

  // ----------------------------------------------------
  // 4. 폼 세부 컴포넌트 (Forms)
  // ----------------------------------------------------
  {
    id: 'form_basic_inputs',
    title: '기본 입력란 (Basic Inputs)',
    subTitle: '텍스트, 이메일, 비밀번호, 플레이스홀더 기본 입력 인풋 컴포넌트',
    path: '/forms/elements',
    categoryKey: 'forms',
    categoryName: '폼 컴포넌트',
    parentMenuName: '폼 > 폼 요소',
    iconName: 'SquarePen',
    keywords: ['기본입력란', '인풋', 'input', 'text input', '비밀번호', '이메일'],
    badge: '9',
  },
  {
    id: 'form_select_options',
    title: '선택 입력란 (Select Options)',
    subTitle: '드롭다운 단일/다중 선택 옵션 컴포넌트',
    path: '/forms/elements',
    categoryKey: 'forms',
    categoryName: '폼 컴포넌트',
    parentMenuName: '폼 > 폼 요소',
    iconName: 'SquarePen',
    keywords: ['선택입력란', '셀렉트', 'select', '드롭다운', 'option'],
  },
  {
    id: 'form_textarea',
    title: '텍스트 영역 (Textarea)',
    subTitle: '장문의 글 작성용 텍스트에리어 입력 필드',
    path: '/forms/elements',
    categoryKey: 'forms',
    categoryName: '폼 컴포넌트',
    parentMenuName: '폼 > 폼 요소',
    iconName: 'SquarePen',
    keywords: ['텍스트영역', 'textarea', '장문입력', '본문작성'],
  },
  {
    id: 'form_input_groups',
    title: '입력 그룹 (Input Groups)',
    subTitle: '접두사/접미사 아이콘, 버튼 결합형 인풋 그룹',
    path: '/forms/elements',
    categoryKey: 'forms',
    categoryName: '폼 컴포넌트',
    parentMenuName: '폼 > 폼 요소',
    iconName: 'SquarePen',
    keywords: ['입력그룹', 'input group', '아이콘인풋', '검색인풋'],
  },
  {
    id: 'form_file_upload',
    title: '파일 업로드 & 드롭존 (File Upload & Dropzone)',
    subTitle: '파일 선택 및 인라인 드래그 앤 드롭 파일 첨부 컴포넌트',
    path: '/forms/elements',
    categoryKey: 'forms',
    categoryName: '폼 컴포넌트',
    parentMenuName: '폼 > 폼 요소',
    iconName: 'SquarePen',
    keywords: ['파일업로드', '드롭존', 'file upload', 'dropzone', '첨부파일'],
  },
  {
    id: 'form_checkbox_radio',
    title: '체크박스 & 라디오 버튼 & 토글 스위치',
    subTitle: '다중 선택 체크박스, 단일 선택 라디오, ON/OFF 스위치 컨트롤',
    path: '/forms/elements',
    categoryKey: 'forms',
    categoryName: '폼 컴포넌트',
    parentMenuName: '폼 > 폼 요소',
    iconName: 'SquarePen',
    keywords: ['체크박스', '라디오', '스위치', 'checkbox', 'radio', 'switch', 'toggle'],
  },

  // ----------------------------------------------------
  // 5. 웹진 - 아르떼 회색 박스 및 서식 (Arte Gray Boxes)
  // ----------------------------------------------------
  {
    id: 'bottom-gray-box-counseling',
    title: '하단 회색 박스(동료 상담실)',
    subTitle: '아르떼365 동료 상담실 안내 문구가 들어간 하단 회색 박스 템플릿',
    path: '/webzine/arte/box',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 박스 양식',
    iconName: 'BookOpen',
    keywords: ['하단 회색 박스', '하단회색박스', '회색 박스', '동료 상담실', '하단 회색 박스(동료 상담실)', '동료상담실', '회색박스', 'arte box'],
    badge: '14',
  },
  {
    id: 'issue-top-gray-box-text-only',
    title: '이슈 상단 회색 박스(글만 있는)',
    subTitle: '기획 연쇄 컬럼 소개글이 담긴 아르떼 상단 회색 박스 템플릿',
    path: '/webzine/arte/box',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 박스 양식',
    iconName: 'BookOpen',
    keywords: ['이슈 상단 회색 박스', '상단 회색 박스', '회색 박스', '글만있는', '회색박스', 'arte box'],
  },
  {
    id: 'gray-box-name-desc',
    title: '회색박스 - 이름/설명',
    subTitle: '발언자 이름과 경험/의견 본문이 담긴 회색 박스 템플릿',
    path: '/webzine/arte/box',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 박스 양식',
    iconName: 'BookOpen',
    keywords: ['회색박스 - 이름/설명', '회색박스', '이름설명', '회색 박스', 'arte box'],
  },
  {
    id: 'top-gray-bg-main-news',
    title: '상단 회색배경 - 주요소식',
    subTitle: '상단에 위치한 아르떼 주요 소식 회색 배경 박스 템플릿',
    path: '/webzine/arte/box',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 박스 양식',
    iconName: 'BookOpen',
    keywords: ['상단 회색배경', '주요소식', '회색배경', '상단 회색 박스', 'arte box'],
  },
  {
    id: 'gray-bg-blue-text-interview',
    title: '회색배경 - 파란 글씨 인터뷰',
    subTitle: '파란색 발언자 강조 텍스트가 적용된 회색 배경 인터뷰 템플릿',
    path: '/webzine/arte/box',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 박스 양식',
    iconName: 'BookOpen',
    keywords: ['회색배경', '파란글씨', '인터뷰', '회색 박스', 'arte box'],
  },
  {
    id: 'gray-bg-alphabetical-profile',
    title: '회색배경 - 가나다순 글 프로필',
    subTitle: '가나다순 필진 및 글 목록 회색 배경 템플릿',
    path: '/webzine/arte/box',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 박스 양식',
    iconName: 'BookOpen',
    keywords: ['회색배경', '가나다순', '프로필', '회색 박스', 'arte box'],
  },
  {
    id: 'gray-bg-scenario',
    title: '회색배경 - 시나리오',
    subTitle: '시나리오 대사 본문 회색 배경 박스 템플릿',
    path: '/webzine/arte/box',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 박스 양식',
    iconName: 'BookOpen',
    keywords: ['회색배경', '시나리오', '회색 박스', 'arte box'],
  },
  {
    id: 'gray-box-no-line-poem',
    title: '회색박스 라인없는 시',
    subTitle: '구분선 없이 깔끔한 회색 박스 시 구절 템플릿',
    path: '/webzine/arte/box',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 박스 양식',
    iconName: 'BookOpen',
    keywords: ['회색박스', '라인없는시', '회색 박스', '시', 'arte box'],
  },
  {
    id: 'related-info-gray-box-report',
    title: '관련자료 회색박스 (리포트)',
    subTitle: '리포트 및 참고 자료 링크가 들어간 회색 박스 템플릿',
    path: '/webzine/arte/box',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 박스 양식',
    iconName: 'BookOpen',
    keywords: ['관련자료', '회색박스', '리포트', '회색 박스', 'arte box'],
  },
  {
    id: 'gray-box-beetle',
    title: '회색 박스 - 비틀',
    subTitle: '아르떼 비틀 기사 인용 회색 박스 템플릿',
    path: '/webzine/arte/box',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 박스 양식',
    iconName: 'BookOpen',
    keywords: ['회색 박스', '비틀', '회색박스', 'arte box'],
  },
  {
    id: 'gray-box-center-line-poem',
    title: '회색 박스 (가운데 라인, 시)',
    subTitle: '가운데 구분선과 시 구절이 들어간 회색 박스 템플릿',
    path: '/webzine/arte/box',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 박스 양식',
    iconName: 'BookOpen',
    keywords: ['회색 박스', '가운데라인', '시', '회색박스', 'arte box'],
  },

  // ----------------------------------------------------
  // 6. 웹진 - 이음 회색 상자 (Eeum Gray Boxes)
  // ----------------------------------------------------
  {
    id: 'ieum-gray-box1',
    title: '이음 - 회색 상자 (질의응답)',
    subTitle: '웹진 이음 회색 박스 질문 및 답변 대화 본문 템플릿',
    path: '/webzine/eeum/box',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 이음 > 박스 양식',
    iconName: 'BookOpen',
    keywords: ['이음', '회색 상자', '회색박스', '질의응답', 'eeum box'],
  },
  {
    id: 'ieum-gray-box2',
    title: '이음 - 회색 상자 (시/문학)',
    subTitle: '웹진 이음 회색 박스 시 구절 및 문학 작품 템플릿',
    path: '/webzine/eeum/box',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 이음 > 박스 양식',
    iconName: 'BookOpen',
    keywords: ['이음', '회색 상자', '시문학', '회색박스', 'eeum box'],
  },

  // ----------------------------------------------------
  // 7. 기타 좌담 & 아르떼 탭 템플릿
  // ----------------------------------------------------
  {
    id: 'discussion-tab-2',
    title: '좌담 탭 2개 (아르떼 탭 레이아웃)',
    subTitle: '2개 버튼으로 구성된 아르떼 웹진 좌담 탭 레이아웃 템플릿',
    path: '/webzine/arte/link',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 링크',
    iconName: 'BookOpen',
    keywords: ['좌담 탭 2개', '좌담탭2개', '좌담', '좌담 탭', '탭', '아르떼 탭', 'arte link'],
    badge: '10',
  },
  {
    id: 'discussion-tab-4',
    title: '좌담 탭 4개 (아르떼 탭 레이아웃)',
    subTitle: '4개 버튼으로 구성된 아르떼 웹진 좌담 탭 레이아웃 템플릿',
    path: '/webzine/arte/link',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 링크',
    iconName: 'BookOpen',
    keywords: ['좌담 탭 4개', '좌담탭4개', '좌담', '좌담 탭', '탭', 'arte link'],
  },
  {
    id: 'discussion-tab-5',
    title: '좌담 탭 5개 (아르떼 탭 레이아웃)',
    subTitle: '5개 버튼으로 구성된 아르떼 웹진 좌담 탭 레이아웃 템플릿',
    path: '/webzine/arte/link',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 링크',
    iconName: 'BookOpen',
    keywords: ['좌담 탭 5개', '좌담탭5개', '좌담', '좌담 탭', '탭', 'arte link'],
  },
  {
    id: 'discussion-image-profile',
    title: '좌담 - 이미지 프로필 (이름 아래 이미지)',
    subTitle: '좌담/토론 참석자 이름과 직함 아래에 프로필 사진이 상하 배치된 템플릿',
    path: '/webzine/arte/new',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > New',
    iconName: 'BookOpen',
    keywords: ['좌담', '좌담 이미지 프로필', '좌담프로필', '이미지프로필', '토론참석자', 'arte new'],
    badge: '12',
  },
  {
    id: 'discussion-overview-lines',
    title: '좌담 개요 (위, 아래 선)',
    subTitle: '위아래 선으로 구분된 깔끔한 좌담 개요 레이아웃 템플릿',
    path: '/webzine/arte/box',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 박스 양식',
    iconName: 'BookOpen',
    keywords: ['좌담 개요', '좌담개요', '좌담', '위아래선', '개요박스', 'arte box'],
  },

  // ----------------------------------------------------
  // 8. UI 쇼케이스 컴포넌트
  // ----------------------------------------------------
  {
    id: 'ui_modals_popups',
    title: '알림창 & 모달 팝업 & 토스트 (Alerts, Modals, Toasts)',
    subTitle: '경고, 성공, 확인 모달 팝업 및 토스트 알림 메시지',
    path: '/ui/alerts-modals',
    categoryKey: 'ui',
    categoryName: 'UI 컴포넌트',
    parentMenuName: 'UI 요소 > 알림 & 모달',
    iconName: 'Component',
    keywords: ['알림', '모달', '팝업', 'modal', 'alert', 'toast', 'dialog'],
    badge: '3',
  },
  {
    id: 'ui_buttons_chips',
    title: '버튼 스타일 & 배지 칩 (Buttons & Badges)',
    subTitle: '프리미엄 컬러 버튼, 로딩 버튼, 상태 배지 태그 모음',
    path: '/ui/buttons-badges',
    categoryKey: 'ui',
    categoryName: 'UI 컴포넌트',
    parentMenuName: 'UI 요소 > 버튼 & 배지',
    iconName: 'Component',
    keywords: ['버튼', '배지', 'button', 'badge', 'chip', '태그'],
    badge: '4',
  },
  {
    id: 'ui_progress_tabs',
    title: '프로그레스바, 탭, 브레드크럼 (Progress & Navigation)',
    subTitle: '진행률 바, 서브 탭 바, 경로 브레드크럼, 단계별 스텝 바',
    path: '/ui/progress-nav',
    categoryKey: 'ui',
    categoryName: 'UI 컴포넌트',
    parentMenuName: 'UI 요소 > 진행률 & 네비게이션',
    iconName: 'Component',
    keywords: ['진행률', '탭', '브레드크럼', 'progress', 'tabs', 'breadcrumb', 'step'],
    badge: '4',
  },
  {
    id: 'ui_skeleton_empty',
    title: '스켈레톤 로더 & 빈 상태 안내 (Skeleton & Empty State)',
    subTitle: '데이터 로딩 시 스켈레톤 애니메이션 및 검색 결과 없음 안내 뷰',
    path: '/ui/states-loaders',
    categoryKey: 'ui',
    categoryName: 'UI 컴포넌트',
    parentMenuName: 'UI 요소 > 상태 & 로더',
    iconName: 'Component',
    keywords: ['스켈레톤', '로더', 'skeleton', 'empty state', '로딩', '빈상태'],
    badge: '2',
  },
];
