export interface SearchIndexItem {
  id: string;
  title: string;          // 타이틀 (한글/영문 컴포넌트 제목)
  subTitle?: string;       // 세부 타이틀 / 설명
  path: string;            // 이동할 URL 라우트
  categoryKey: string;     // 카테고리 식별자
  categoryName: string;    // 카테고리 표시 이름
  parentMenuName?: string; // 상위 메뉴 이름
  iconName: string;        // Lucide 아이콘 이름
  keywords: string[];      // 검색 키워드/태그 리스트
  badge?: string;          // 배지
}

export const searchableIndex: SearchIndexItem[] = [
  // ----------------------------------------------------
  // 1. 대시보드 (Dashboard)
  // ----------------------------------------------------
  {
    id: 'dashboard_main',
    title: '대시보드 메인',
    subTitle: '월별 컴포넌트 추이 / 고객 인구 통계 / 최근 주문 현황',
    path: '/',
    categoryKey: 'dashboard',
    categoryName: '대시보드',
    iconName: 'LayoutDashboard',
    keywords: ['대시보드', '메인', '월별', '추이', '인구통계', '최근주문', '통계', '차트', 'dashboard'],
  },
  {
    id: 'dashboard_recent_orders',
    title: '최근 주문 및 개발 활동 로그',
    subTitle: '대시보드 내 최근 컴포넌트 업데이트 및 커밋 히스토리',
    path: '/',
    categoryKey: 'dashboard',
    categoryName: '대시보드',
    iconName: 'LayoutDashboard',
    keywords: ['주문', '활동', '로그', '커밋', '히스토리', '업데이트', '개발'],
  },

  // ----------------------------------------------------
  // 2. 히어로 섹션 세부 컴포넌트 (Hero Sections)
  // ----------------------------------------------------
  {
    id: 'hero_yongin',
    title: '용인디지털기록관 히어로 (바닐라 JS & Tailwind)',
    subTitle: '용인디지털기록관 메인 페이드 슬라이더 및 타이틀 비주얼 히어로 컴포넌트',
    path: '/pages/hero-sections',
    categoryKey: 'pages',
    categoryName: '페이지 컴포넌트',
    parentMenuName: '페이지 > 히어로 섹션',
    iconName: 'Layers',
    keywords: ['용인디지털기록관', '용인디지털기록관 히어로', '용인', '기록관', '임진산성', '처인성', '슬라이더', '페이드', 'hero', '디지털기록관'],
    badge: 'NEW',
  },
  {
    id: 'hero_centered',
    title: '간단한 중앙 정렬 히어로',
    subTitle: '모던 텍스트 배치 및 행동 유도(CTA) 버튼 중앙 히어로 컴포넌트',
    path: '/pages/hero-sections',
    categoryKey: 'pages',
    categoryName: '페이지 컴포넌트',
    parentMenuName: '페이지 > 히어로 섹션',
    iconName: 'Layers',
    keywords: ['중앙정렬', '히어로', 'cta', '텍스트히어로', '중앙', 'simple hero'],
  },
  {
    id: 'hero_split',
    title: '클래식 분할 배치 히어로',
    subTitle: '좌측 타이틀 설명 텍스트, 우측 이미지 그래픽 분할 히어로',
    path: '/pages/hero-sections',
    categoryKey: 'pages',
    categoryName: '페이지 컴포넌트',
    parentMenuName: '페이지 > 히어로 섹션',
    iconName: 'Layers',
    keywords: ['분할', '클래식', '이미지히어로', '좌우분할', 'split hero'],
  },
  {
    id: 'hero_elegant',
    title: '우아한 분위기의 중앙 정렬 히어로',
    subTitle: '글래스모피즘 및 다크 모드 스타일이 적용된 프리미엄 비주얼 히어로',
    path: '/pages/hero-sections',
    categoryKey: 'pages',
    categoryName: '페이지 컴포넌트',
    parentMenuName: '페이지 > 히어로 섹션',
    iconName: 'Layers',
    keywords: ['우아한', '프리미엄', '글래스모피즘', 'dark hero', 'elegant hero'],
  },
  {
    id: 'hero_search',
    title: '검색 포커스형 가이드 히어로 (Search Oriented Hero)',
    subTitle: '중앙 대형 검색창 및 인기 키워드 태그가 포함된 검색 가이드 히어로',
    path: '/pages/hero-sections',
    categoryKey: 'pages',
    categoryName: '페이지 컴포넌트',
    parentMenuName: '페이지 > 히어로 섹션',
    iconName: 'Layers',
    keywords: ['검색', '검색포커스', '검색형히어로', 'search hero', '인기검색어', '가이드'],
  },
  {
    id: 'hero_minimal',
    title: '미니멀 이미지 배경 히어로',
    subTitle: '깔끔하고 정돈된 비주얼 배경 히어로 섹션',
    path: '/pages/hero-sections',
    categoryKey: 'pages',
    categoryName: '페이지 컴포넌트',
    parentMenuName: '페이지 > 히어로 섹션',
    iconName: 'Layers',
    keywords: ['미니멀', '배경이미지', 'minimal hero', '깔끔한'],
  },

  // ----------------------------------------------------
  // 3. 테이블 세부 컴포넌트 (Tables)
  // ----------------------------------------------------
  {
    id: 'table_recent_orders',
    title: '최근 주문 테이블 (Recent Orders Table)',
    subTitle: '체크박스, 거래 ID, 고객 정보, 마감일, 상태 배지가 포함된 테이블',
    path: '/tables/basic',
    categoryKey: 'tables',
    categoryName: '테이블 컴포넌트',
    parentMenuName: '테이블 > 기본 테이블',
    iconName: 'Table',
    keywords: ['최근주문', '주문테이블', '고객목록', 'orders table', '거래ID', '체크박스'],
    badge: '5',
  },
  {
    id: 'table_recent_transactions',
    title: '최근 거래 내역 테이블 (Recent Transactions Table)',
    subTitle: '아이콘, 카테고리, 거래 금액, 처리 상태 표기 테이블',
    path: '/tables/basic',
    categoryKey: 'tables',
    categoryName: '테이블 컴포넌트',
    parentMenuName: '테이블 > 기본 테이블',
    iconName: 'Table',
    keywords: ['최근거래', '거래내역', '입출금', 'transactions table', '금융테이블'],
  },

  // ----------------------------------------------------
  // 4. 폼 세부 컴포넌트 (Forms)
  // ----------------------------------------------------
  {
    id: 'form_basic_inputs',
    title: '기본 입력란 (Basic Inputs)',
    subTitle: '텍스트, 이메일, 비밀번호, 플레이스홀더 기본 입력 인풋 컴포넌트',
    path: '/forms/elements',
    categoryKey: 'forms',
    categoryName: '폼 컴포넌트',
    parentMenuName: '폼 > 폼 요소',
    iconName: 'SquarePen',
    keywords: ['기본입력란', '인풋', 'input', 'text input', '비밀번호', '이메일'],
    badge: '9',
  },
  {
    id: 'form_select_options',
    title: '선택 입력란 (Select Options)',
    subTitle: '드롭다운 단일/다중 선택 옵션 컴포넌트',
    path: '/forms/elements',
    categoryKey: 'forms',
    categoryName: '폼 컴포넌트',
    parentMenuName: '폼 > 폼 요소',
    iconName: 'SquarePen',
    keywords: ['선택입력란', '셀렉트', 'select', '드롭다운', 'option'],
  },
  {
    id: 'form_textarea',
    title: '텍스트 영역 (Textarea)',
    subTitle: '장문의 글 작성용 텍스트에리어 입력 필드',
    path: '/forms/elements',
    categoryKey: 'forms',
    categoryName: '폼 컴포넌트',
    parentMenuName: '폼 > 폼 요소',
    iconName: 'SquarePen',
    keywords: ['텍스트영역', 'textarea', '장문입력', '본문작성'],
  },
  {
    id: 'form_input_groups',
    title: '입력 그룹 (Input Groups)',
    subTitle: '접두사/접미사 아이콘, 버튼 결합형 인풋 그룹',
    path: '/forms/elements',
    categoryKey: 'forms',
    categoryName: '폼 컴포넌트',
    parentMenuName: '폼 > 폼 요소',
    iconName: 'SquarePen',
    keywords: ['입력그룹', 'input group', '아이콘인풋', '검색인풋'],
  },
  {
    id: 'form_file_upload',
    title: '파일 업로드 & 드롭존 (File Upload & Dropzone)',
    subTitle: '파일 선택 및 인라인 드래그 앤 드롭 파일 첨부 컴포넌트',
    path: '/forms/elements',
    categoryKey: 'forms',
    categoryName: '폼 컴포넌트',
    parentMenuName: '폼 > 폼 요소',
    iconName: 'SquarePen',
    keywords: ['파일업로드', '드롭존', 'file upload', 'dropzone', '첨부파일'],
  },
  {
    id: 'form_checkbox_radio',
    title: '체크박스 & 라디오 버튼 & 토글 스위치',
    subTitle: '다중 선택 체크박스, 단일 선택 라디오, ON/OFF 스위치 컨트롤',
    path: '/forms/elements',
    categoryKey: 'forms',
    categoryName: '폼 컴포넌트',
    parentMenuName: '폼 > 폼 요소',
    iconName: 'SquarePen',
    keywords: ['체크박스', '라디오', '스위치', 'checkbox', 'radio', 'switch', 'toggle'],
  },
  {
    id: 'form_signup_layout',
    title: '회원가입 & 상세 개인정보 입력 폼 레이아웃',
    subTitle: '이름, 주소, 연락처, 카드 결제 입력 종합 폼 서식',
    path: '/forms/layout',
    categoryKey: 'forms',
    categoryName: '폼 컴포넌트',
    parentMenuName: '폼 > 폼 레이아웃',
    iconName: 'SquarePen',
    keywords: ['회원가입폼', '개인정보폼', '주소폼', 'signup form', 'layout form'],
    badge: '4',
  },
  {
    id: 'component_input_showcase',
    title: '인풋 컴포넌트 스타일 쇼케이스',
    subTitle: '포커스 애니메이션, 검증 상태별 인풋 컴포넌트 모음',
    path: '/components/input',
    categoryKey: 'ui',
    categoryName: 'UI 요소',
    parentMenuName: 'UI 요소 > 인풋',
    iconName: 'Component',
    keywords: ['인풋쇼케이스', '입력창', 'focus input', 'custom input'],
    badge: '1',
  },

  // ----------------------------------------------------
  // 5. 가격 정책 섹션 세부 컴포넌트 (Pricing Sections)
  // ----------------------------------------------------
  {
    id: 'pricing_highlight_right',
    title: '우측이 강조된 두 가지 티어 요금제',
    subTitle: '스타트업/프로 플랜 우측 추천 강조 카드가 포함된 가격표',
    path: '/pages/pricing-sections',
    categoryKey: 'pages',
    categoryName: '페이지 컴포넌트',
    parentMenuName: '페이지 > 가격 정책 섹션',
    iconName: 'Layers',
    keywords: ['요금제', '가격표', 'pricing', '우측강조', '플랜비교'],
    badge: '4',
  },
  {
    id: 'pricing_three_tiers',
    title: '본문이 강조되는 3가지 티어 요금제',
    subTitle: '베이직, 프로, 엔터프라이즈 센터 강조 가격 카드',
    path: '/pages/pricing-sections',
    categoryKey: 'pages',
    categoryName: '페이지 컴포넌트',
    parentMenuName: '페이지 > 가격 정책 섹션',
    iconName: 'Layers',
    keywords: ['3가지티어', '3단요금제', '센터강조', 'pricing table'],
  },

  // ----------------------------------------------------
  // 6. 차트 세부 컴포넌트 (Line Charts)
  // ----------------------------------------------------
  {
    id: 'chart_basic_line',
    title: '기본 라인 차트 (Basic Line Chart)',
    subTitle: 'Echarts 기반 월별 데이터 추이 기본 선 그래프',
    path: '/charts/line-charts',
    categoryKey: 'applications',
    categoryName: 'APP 컴포넌트',
    parentMenuName: 'APP > Echarts 라인 차트',
    iconName: 'Grid',
    keywords: ['기본라인차트', '선그래프', 'line chart', 'echarts'],
    badge: '11',
  },
  {
    id: 'chart_stacked_area',
    title: '스택형 영역 라인 차트 (Stacked Area Chart)',
    subTitle: '누적 영역 그라데이션 라인 차트 그래프',
    path: '/charts/line-charts',
    categoryKey: 'applications',
    categoryName: 'APP 컴포넌트',
    parentMenuName: 'APP > Echarts 라인 차트',
    iconName: 'Grid',
    keywords: ['스택차트', '영역차트', 'stacked area', '그라데이션차트'],
  },
  {
    id: 'chart_dynamic_step',
    title: '스텝 & 다이내믹 라인 차트 (Step & Dynamic Line)',
    subTitle: '단계별 계단형 차트 및 실시간 동적 신호 라인 그래프',
    path: '/charts/line-charts',
    categoryKey: 'applications',
    categoryName: 'APP 컴포넌트',
    parentMenuName: 'APP > Echarts 라인 차트',
    iconName: 'Grid',
    keywords: ['스텝차트', '계단형차트', '다이내믹차트', 'step line', 'dynamic chart'],
  },
  {
    id: 'app_calendar_interactive',
    title: '인터랙티브 이벤트 캘린더 (Interactive Calendar)',
    subTitle: '월간/주간 일정 추가, 선택, 필터링이 가능한 캘린더 컴포넌트',
    path: '/calendar',
    categoryKey: 'applications',
    categoryName: 'APP 컴포넌트',
    parentMenuName: 'APP > 캘린더',
    iconName: 'Grid',
    keywords: ['캘린더', '달력', '일정관리', '이벤트', 'calendar'],
    badge: '1',
  },

  // ----------------------------------------------------
  // 7. 기타 페이지 컴포넌트 (FAQ, Integrations, Errors)
  // ----------------------------------------------------
  {
    id: 'faq_accordion',
    title: '자주 묻는 질문 FAQ (Accordion & Tabs)',
    subTitle: '카테고리 탭, 아코디언 토글, 질문 검색어 포함 FAQ 섹션',
    path: '/pages/faq',
    categoryKey: 'pages',
    categoryName: '페이지 컴포넌트',
    parentMenuName: '페이지 > FAQ',
    iconName: 'Layers',
    keywords: ['faq', '질문', '답변', '자주묻는질문', '아코디언', 'qna'],
    badge: '3',
  },
  {
    id: 'integrations_cards',
    title: '연동 서비스 관리 카드 (Slack, GitHub, Figma 등)',
    subTitle: '외부 앱/플랫폼 연결 및 토글 스위치 설정 카드 모음',
    path: '/pages/integrations',
    categoryKey: 'pages',
    categoryName: '페이지 컴포넌트',
    parentMenuName: '페이지 > 연동',
    iconName: 'Layers',
    keywords: ['연동', '인테그레이션', 'slack', 'github', 'figma', 'notion', 'integration'],
    badge: '1',
  },
  {
    id: 'error_pages_group',
    title: '에러 상태 페이지 모음 (404, 500, 503 Error Pages)',
    subTitle: '404 페이지 찾을 수 없음 / 500 서버 오류 / 503 서비스 점검 화면',
    path: '/pages/error-404',
    categoryKey: 'pages',
    categoryName: '페이지 컴포넌트',
    parentMenuName: '페이지 > 에러',
    iconName: 'Layers',
    keywords: ['에러', '404', '500', '503', '오류', 'not found', 'error page'],
    badge: '1',
  },

  // ----------------------------------------------------
  // 8. UI 요소 쇼케이스 (UI Showcase)
  // ----------------------------------------------------
  {
    id: 'ui_modals_popups',
    title: '알림창 & 모달 팝업 & 토스트 (Alerts, Modals, Toasts)',
    subTitle: '경고, 성공, 확인 모달 팝업 및 토스트 알림 메시지',
    path: '/ui/alerts-modals',
    categoryKey: 'ui',
    categoryName: 'UI 컴포넌트',
    parentMenuName: 'UI 요소 > 알림 & 모달',
    iconName: 'Component',
    keywords: ['알림', '모달', '팝업', 'modal', 'alert', 'toast', 'dialog'],
    badge: '3',
  },
  {
    id: 'ui_buttons_chips',
    title: '버튼 스타일 & 배지 칩 (Buttons & Badges)',
    subTitle: '프리미엄 컬러 버튼, 로딩 버튼, 상태 배지 태그 모음',
    path: '/ui/buttons-badges',
    categoryKey: 'ui',
    categoryName: 'UI 컴포넌트',
    parentMenuName: 'UI 요소 > 버튼 & 배지',
    iconName: 'Component',
    keywords: ['버튼', '배지', 'button', 'badge', 'chip', '태그'],
    badge: '4',
  },
  {
    id: 'ui_progress_tabs',
    title: '프로그레스바, 탭, 브레드크럼 (Progress & Navigation)',
    subTitle: '진행률 바, 서브 탭 바, 경로 브레드크럼, 단계별 스텝 바',
    path: '/ui/progress-nav',
    categoryKey: 'ui',
    categoryName: 'UI 컴포넌트',
    parentMenuName: 'UI 요소 > 진행률 & 네비게이션',
    iconName: 'Component',
    keywords: ['진행률', '탭', '브레드크럼', 'progress', 'tabs', 'breadcrumb', 'step'],
    badge: '4',
  },
  {
    id: 'ui_skeleton_empty',
    title: '스켈레톤 로더 & 빈 상태 안내 (Skeleton & Empty State)',
    subTitle: '데이터 로딩 시 스켈레톤 애니메이션 및 검색 결과 없음 안내 뷰',
    path: '/ui/states-loaders',
    categoryKey: 'ui',
    categoryName: 'UI 컴포넌트',
    parentMenuName: 'UI 요소 > 상태 & 로더',
    iconName: 'Component',
    keywords: ['스켈레톤', '로더', 'skeleton', 'empty state', '로딩', '빈상태'],
    badge: '2',
  },

  // ----------------------------------------------------
  // 9. 웹진 - 이음 세부 컴포넌트 (Eeum Webzine)
  // ----------------------------------------------------
  {
    id: 'eeum_text_comp',
    title: '이음 - 본문 텍스트 & 인터뷰 양식 (Eeum Text)',
    subTitle: '웹진 이음 본문 타이틀, 소제목, 필진 서문, 기사 인터뷰 템플릿',
    path: '/webzine/eeum/text',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 이음 > 텍스트',
    iconName: 'BookOpen',
    keywords: ['이음텍스트', '이음', 'eeum text', '웹진텍스트', '인터뷰', '본문'],
    badge: '18',
  },
  {
    id: 'eeum_box_comp',
    title: '이음 - 강조 박스 & 인용구 서식 (Eeum Box)',
    subTitle: '인용 박스, 요약 가이드 박스, 컬러 포인트 테두리 박스',
    path: '/webzine/eeum/box',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 이음 > 박스 양식',
    iconName: 'BookOpen',
    keywords: ['이음박스', 'eeum box', '강조박스', '인용구', '요약박스'],
    badge: '17',
  },
  {
    id: 'eeum_image_comp',
    title: '이음 - 이미지 화보 & 갤러리 (Eeum Image)',
    subTitle: '단일/다중 이미지 배치, 캡션, 갤러리 슬라이드 컴포넌트',
    path: '/webzine/eeum/image',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 이음 > 이미지',
    iconName: 'BookOpen',
    keywords: ['이음이미지', 'eeum image', '화보', '갤러리', '사진배치'],
    badge: '11',
  },
  {
    id: 'eeum_link_comp',
    title: '이음 - 관련 기사 & 링크 (Eeum Link)',
    subTitle: '관련 웹진 페이지 링크 카드, 팟캐스트 A의 모든 것 링크',
    path: '/webzine/eeum/link',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 이음 > 링크',
    iconName: 'BookOpen',
    keywords: ['이음링크', 'eeum link', '관련기사', '팟캐스트', 'a의모든것'],
    badge: '3',
  },
  {
    id: 'eeum_video_comp',
    title: '이음 - 영상 동영상 임베드 (Eeum Video)',
    subTitle: '유튜브/Vimeo 웹진 동영상 플레이어 및 출처 표기 영역',
    path: '/webzine/eeum/video',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 이음 > 영상',
    iconName: 'BookOpen',
    keywords: ['이음영상', 'eeum video', '유튜브비디오', '동영상플레이어'],
    badge: '3',
  },
  {
    id: 'eeum_profile_comp',
    title: '이음 - 필진 프로필 카드 (Eeum Profile)',
    subTitle: '필자 사진, 이력, 소개글이 담긴 아티스트/저자 프로필',
    path: '/webzine/eeum/profile',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 이음 > 프로필',
    iconName: 'BookOpen',
    keywords: ['이음프로필', 'eeum profile', '필진소개', '저자프로필'],
    badge: '14',
  },
  {
    id: 'eeum_table_comp',
    title: '이음 - 웹진 요약 표 (Eeum Table)',
    subTitle: '웹진 본문용 깔끔한 정렬 요약 표 서식',
    path: '/webzine/eeum/table',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 이음 > 표',
    iconName: 'BookOpen',
    keywords: ['이음표', 'eeum table', '요약표', '정보테이블'],
    badge: '6',
  },

  // ----------------------------------------------------
  // 10. 웹진 - 아르떼 세부 컴포넌트 (Arte Webzine)
  // ----------------------------------------------------
  {
    id: 'arte_image_comp',
    title: '아르떼 - 비주얼 이미지 & 전시 화보 (Arte Image)',
    subTitle: '아르떼365 예술/전시 화보 이미지 및 사진 템플릿',
    path: '/webzine/arte/image',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 이미지',
    iconName: 'BookOpen',
    keywords: ['아르떼이미지', 'arte image', '전시화보', '아르떼365'],
    badge: '16',
  },
  {
    id: 'arte_link_comp',
    title: '아르떼 - a 태그 링크 서식 (Arte Link)',
    subTitle: '공유마당, 아르코 입장문 등 아르떼 하이퍼링크 양식',
    path: '/webzine/arte/link',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 링크',
    iconName: 'BookOpen',
    keywords: ['아르떼링크', 'arte link', 'a태그', '공유마당', '입장문'],
    badge: '10',
  },
  {
    id: 'arte_video_comp',
    title: '아르떼 - 공연 & 미디어 영상 (Arte Video)',
    subTitle: '예술 공연, 전시 현장 동영상 미디어 플레이어 서식',
    path: '/webzine/arte/video',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 영상',
    iconName: 'BookOpen',
    keywords: ['아르떼영상', 'arte video', '공연영상', '전시미디어'],
    badge: '4',
  },
  {
    id: 'arte_text_comp',
    title: '아르떼 - 예술 칼럼 & 글씨 서식 (Arte Text)',
    subTitle: '아르떼 예술 칼럼, 타이포그래피, 본문 텍스트 서식',
    path: '/webzine/arte/text',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 글씨',
    iconName: 'BookOpen',
    keywords: ['아르떼글씨', 'arte text', '예술칼럼', '타이포그래피'],
    badge: '16',
  },
  {
    id: 'arte_profile_comp',
    title: '아르떼 - 아티스트 프로필 (Arte Profile)',
    subTitle: '아티스트, 기획자, 작가 카모마일/린데블라드 프로필 서식',
    path: '/webzine/arte/profile',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 프로필',
    iconName: 'BookOpen',
    keywords: ['아르떼프로필', 'arte profile', '아티스트소개', '작가프로필'],
    badge: '9',
  },
  {
    id: 'arte_box_comp',
    title: '아르떼 - 테두리 박스 양식 (Arte Box)',
    subTitle: '비욘 나티코 린데블라드 책 소개 및 테두리 박스 서식',
    path: '/webzine/arte/box',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 박스 양식',
    iconName: 'BookOpen',
    keywords: ['아르떼박스', 'arte box', '린데블라드', '내가틀릴수도있습니다', '박스서식'],
    badge: '14',
  },
  {
    id: 'arte_new_comp',
    title: '아르떼 - New 신규 컴포넌트 (Arte New)',
    subTitle: '최신 릴리즈된 아르떼 전용 템플릿 컴포넌트 모음',
    path: '/webzine/arte/new',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > New',
    iconName: 'BookOpen',
    keywords: ['아르떼new', 'arte new', '신규아르떼', '최신템플릿'],
    badge: '12',
  },
  {
    id: 'arte_table_comp',
    title: '아르떼 - 행사 일정 & 정보 표 (Arte Table)',
    subTitle: '아르떼 행사/전시 일정 안내 데이터 표 서식',
    path: '/webzine/arte/table',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 표',
    iconName: 'BookOpen',
    keywords: ['아르떼표', 'arte table', '전시일정표', '행사표'],
    badge: '4',
  },
  {
    id: 'arte_notice_comp',
    title: '아르떼 - 공지사항 & 이벤트 배너 (Arte Notice)',
    subTitle: '아르떼 이벤트 안내, 공지 배너 및 안내문 서식',
    path: '/webzine/arte/notice',
    categoryKey: 'webzine',
    categoryName: '웹진 컴포넌트',
    parentMenuName: '웹진 > 아르떼 > 공지사항 이벤트',
    iconName: 'BookOpen',
    keywords: ['아르떼공지', 'arte notice', '공지사항', '이벤트배너', '안내문'],
    badge: '6',
  },
];
